name: Deploy to Github Pages

on:
  push:
    branches: ["ci-test"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install Packages
        run: yarn
      - name: Run Lint
        run: yarn lint
      - name: Build portfolio
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build/
          if-no-files-found: error
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout Deployment Repository
        uses: actions/checkout@v4
        with:
          repository: rohanmohapatra/rohanmohapatra.github.io
          ref: master
          path: deploy
      - name: Change cwd and clean up repository
        working-directory: ./deploy
        run: |
          git rm -rf .
      - uses: actions/download-artifact@v4
        working-directory: ./deploy
        with:
          name: github-pages
          path: .
      - working-directory: ./deploy
        run: ls -al