name: Deploy to Github Pages

on:
  push:
    branches: ["ci-test"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install Packages
        run: yarn
      - name: Run Lint
        run: yarn lint
      - name: Build portfolio
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: .
      - run: ls -R