name: Deploy to Github Pages

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install Packages
        run: yarn
      - name: Run Typegen
        run: npx @chakra-ui/cli typegen ./src/lib/theme.ts
      - name: Run Lint
        run: yarn lint
      - name: Build Application
        run: yarn build
      - name: Add .nojekyll file
        run: |
          touch ./build/.nojekyll
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build/
          if-no-files-found: error
          include-hidden-files: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./build_artifact

      - name: Checkout Deployment Repository
        uses: actions/checkout@v4
        with:
          repository: rohanmohapatra/rohanmohapatra.github.io
          ref: master
          path: deploy
          token: ${{ secrets.PAT_TOKEN }}

      - name: Sync files and commit
        working-directory: ./deploy
        run: |
          rsync -av --delete --exclude 'versions' --exclude '.git' ../build_artifact/ .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit. Website is up to date."
            exit 0
          fi
          git add --all
          git commit -m "Deploy website - based on ${{ github.sha }}"
          git push origin HEAD

      - name: Set deployment URL output
        id: deployment
        run: echo "new_page_url=https://rohanmohapatra.github.io/" >> $GITHUB_OUTPUT
